import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Profile.module.scss'
import PageLayout from '@/layouts/PageLayout/PageLayout'
import LandingBanner from '@/components/index/LandingBanner/LandingBanner'
import BasicContainer from '@/layouts/Containers/BasicContainer/BasicContainer'
import BlurPaper from '@/layouts/Papers/BlurPaper/BlurPaper'
import Features from '@/components/index/Features/Features'
import BluredContainer from '@/layouts/Containers/BluredContainer/BluredContainer'
import Description from '@/components/index/Description/Description'
import LargeGap from '@/components/gaps/large/LargeGap'
import { create } from 'domain'
import { useEffect, useState } from 'react'
import ChainSelect from '@/components/create/ChainSelect/ChainSelect'
import KeySelect from '@/components/create/KeySelect/KeySelect'
import RecoverySigners from '@/components/create/RecoverySigners/RecoverySigners'
import SecurityFeatures from '@/components/create/SecurityFeatures/SecurityFeatures'
import ProfileCreate from '@/components/create/ProfileCreate/ProfileCreate'
import { withPageAuthRequired } from '@auth0/nextjs-auth0'
import { useUser } from '@auth0/nextjs-auth0/client'
import { useAccount } from 'wagmi'
import ChainLaunch from '@/components/Launch/ChainLaunch/ChainLaunch'
import { ethers } from 'ethers'
import axios from 'axios'
import ButtonOutline from '@/components/Buttons/ButtonOutline/ButtonOutline'
import { useConfig } from '@/api/config'

interface RecoverySigner {
    name: string
    email: string
    address: string
}


function Profile() {

    const [userMetdata, setUserMetadata] = useState({})


    const [submitting, setSubmitting] = useState(false)

    const { user, error, isLoading } = useUser();
    const { address, isConnected } = useAccount()
    const { chains } = useConfig()

    const [keyManagement, setKeyManagement] = useState("cust")
    const [publicKey, setPublicKey] = useState("")

    const [recoverySigners, setRecoverySigners] = useState([{ name: "", email: "", address: "" }])

    // useEffect(() => {
    //   if(user != null){
    //     var options = {
    //       method: "get",
    //       url: `https://dev-27jeufvx256r244q.us.auth0.com/api/v2/users-by-email`,
    //       params: {email: `${user.email}`},
    //       headers: {authorization: `Bearer ${process.env.AUTH0_MANAGEMENT_API}`}
    //     };

    //     //@ts-ignore
    //     axios.request(options).then(function (response) {
    //       setUserMetadata(response.data)
    //       console.log(response.data)
    //     }).catch(function (error) {
    //       console.error(error);
    //     });
    //   }
    // }, [user])


    return (
        <>
            <Head>
                <title>Novusys Smart Wallets</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageLayout>
                <div className={styles['header__container']}>
                    <div className={styles['title__container']}>
                        Welcome back <a>{user?.nickname}</a>
                    </div>
                </div>
                <div className={styles['profile__paper']}>
                    <BlurPaper>
                        <div className={styles['profile']}>
                            <div className={styles['left__paper']}>
                                <div className={styles['profile__info']}>
                                    {/* //@ts-ignore */}
                                    <img src={user?.picture == null? undefined: user?.picture}></img>
                                    <div className={styles['user__info']}>
                                        <div className={styles['user__name']}>
                                            {user?.nickname}
                                        </div>
                                        <div className={styles['user__title']}>
                                            Web3 Builder @ Novusys
                                        </div>
                                        <div className={styles['user__desc']}>
                                            Focused on building a bigger and better Web3 Future.
                                        </div>
                                    </div>
                                </div>
                                <div className={styles['below__profile']}>
                                    <div className={styles['chains']}>
                                        <div className={styles['chain']}>
                                            <img src={chains[5].logo}>
                                            </img>
                                            <div className={styles['chain__title']}>
                                                {chains[5].chain}
                                            </div>
                                            <div className={styles['chain__address']}>
                                                0x3D9b8a7A09d1740789DC7C6C62924fc88073a908
                                            </div>

                                        </div>
                                        <div className={styles['chain']}>
                                            <img src={chains[80001].logo}>
                                            </img>
                                            <div className={styles['chain__title']}>
                                                {chains[80001].chain}
                                            </div>
                                            <div className={styles['chain__address']}>
                                                0x3D9b8a7A09d1740789DC7C6C62924fc88073a908
                                            </div>

                                        </div>
                                        <div className={styles['chain']}>
                                            <img src={chains[420].logo}>
                                            </img>
                                            <div className={styles['chain__title']}>
                                                {chains[420].chain}
                                            </div>
                                            <div className={styles['chain__address']}>
                                                0x3D9b8a7A09d1740789DC7C6C62924fc88073a908
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className={styles['right__paper']}>
                                <div className={styles['continue__button']}>
                                    Pause All Wallets
                                </div>
                                <div className={styles['stats']}>
                                    75 <div>Transactions</div>
                                </div>
                                <div className={styles['stats']}>
                                    $30 <div>Gas Saved</div>
                                </div>
                            </div>
                        </div>
                    </BlurPaper>
                </div>
                <BluredContainer>
                    <div className={styles['cards']}>
                        <div className={styles['cards__title']}>
                            Smart Wallets
                        </div>
                        <div className={styles['cards__container']}>
                            Coming Soon
                        </div>
                    </div>
                    <div className={styles['cards']}>
                        <div className={styles['cards__title']}>
                            Dapps
                        </div>
                        <div className={styles['cards__container']}>
                            Coming Soon
                        </div>
                    </div>
                    <div className={styles['cards']}>
                        <div className={styles['cards__title']}>
                            Address Book
                        </div>
                        <div className={styles['cards__container']}>
                            Coming Soon
                        </div>
                    </div>
                </BluredContainer>

            </PageLayout>


        </>
    )
}

// export default withPageAuthRequired(Create);
export const getServerSideProps = withPageAuthRequired()
export default Profile
