name: Deploy Novusys

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/setup-node@v3
      - run: pwd
      - run: ls -l
      - run: npm i
      - run: npm run build --if-present
