name: Deploy Novusys

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          
      - name: Install and build
        run: |
          cd backend
          npm install
          npm run build --if-present

#      - name: Deploy to AWS EC2
#        uses: burnett01/rsync-deployments@5.1
#        with:
#          switches: -avzr --delete
#          path: ./*
#          remote_path: /home/ubuntu/development
#          remote_host: ${{ secrets.NOVUSYS_PRODUCTION_2_HOSTNAME }}
#          remote_user: ${{ secrets.NOVUSYS_PRODUCTION_2_USERNAME }}
#          remote_key: "${{ secrets.NOVUSYS_PRODUCTION_2_PRIVATE_KEY }}"

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: "${{ secrets.NOVUSYS_PRODUCTION_2_PRIVATE_KEY }}"
            HOSTNAME : ${{ secrets.NOVUSYS_PRODUCTION_2_HOSTNAME }}
            USER_NAME : ${{ secrets.NOVUSYS_PRODUCTION_2_USERNAME }}
            PRISMA_ENV : ${{ secrets.NOVUSYS_PRODUCTION_2_PRISMA_ENV }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key.pem && 
          chmod 600 private_key.pem &&
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
            cd development/novusys &&
            export NVM_DIR=~/.nvm &&
            source ~/.nvm/nvm.sh &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            cd backend &&
            echo $PRISMA_ENV > .env &&
            ls -la .env &&
            npm install &&
            npm run build
          '        
