name: Deploy Novusys

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
          
      - name: Install and build
        run: |
          cd backend
          npm install
          nm run build --if-present
